### ISSUE TITLE
Artefatos da Infraestrutura do Provedor

### ISSUE THREAD

**Issue by SilvioAlexsander** [SilvioAlexsander/Projeto-Final--Cafe-e-Kernel#2]
Códigos versionados, relatório de testes e manual de implantação (passo a passo em vídeo)

**Comment by laubatistaa** [comment]
Ótimo! Com base na imagem que você enviou e no seu objetivo de configurar uma infraestrutura DevOps com microsserviços, HAProxy, SSL, serviço de e-mail e integração com GitHub, aqui está um **passo a passo detalhado** para configurar o servidor com os serviços destacados no quadrado vermelho:

---

### 🧱 **1. Estrutura Geral do Servidor**
Você terá um servidor central com os seguintes serviços:
- **HAProxy (Proxy Reverso)** nas portas 80 (HTTP) e 443 (HTTPS)
- **Serviço de E-mail** (SMTP: 25/587, IMAP: 993)
- **Webmail**
- **Servidor DNS** (TCP/UDP 53)
- **Portal Web**

---

### 🔐 **2. Configuração do HAProxy com SSL**
**Objetivo:** Balancear carga e fazer proxy reverso para os serviços internos com HTTPS.

**Passos:**
1. **Instalar o HAProxy:**
   ```bash
   sudo apt update && sudo apt install haproxy -y
   ```

2. **Gerar ou obter certificados SSL:**
   - Use Let's Encrypt com Certbot:
     ```bash
     sudo apt install certbot python3-certbot-nginx -y
     sudo certbot certonly --standalone -d seu-dominio.com
     ```

3. **Configurar o HAProxy:**
   Exemplo de configuração em `/etc/haproxy/haproxy.cfg`:
   ```haproxy
   frontend https_front
       bind *:443 ssl crt /etc/letsencrypt/live/seu-dominio.com/fullchain.pem key /etc/letsencrypt/live/seu-dominio.com/privkey.pem
       mode http
       default_backend web_services

   backend web_services
       server portal 127.0.0.1:8080 check
       server webmail 127.0.0.1:8081 check
   ```

---

### 📧 **3. Configuração do Servidor de E-mail**
**Objetivo:** Enviar e receber e-mails com suporte a Webmail.

**Componentes sugeridos:**
- **Postfix** (SMTP)
- **Dovecot** (IMAP)
- **Roundcube** (Webmail)

**Passos:**
1. **Instalar Postfix e Dovecot:**
   ```bash
   sudo apt install postfix dovecot-core dovecot-imapd -y
   ```

2. **Configurar Postfix para SMTP (25/587):**
   - Editar `/etc/postfix/main.cf` com domínio, TLS, etc.

3. **Configurar Dovecot para IMAP (993):**
   - Editar `/etc/dovecot/dovecot.conf` e `/etc/dovecot/conf.d/10-ssl.conf`

4. **Instalar Roundcube (Webmail):**
   ```bash
   sudo apt install roundcube roundcube-core roundcube-mysql roundcube-plugins
   ```

---

### 🌐 **4. Configuração do Servidor DNS**
**Objetivo:** Resolver nomes internos e externos.

**Passos:**
1. **Instalar Bind9:**
   ```bash
   sudo apt install bind9 bind9utils bind9-doc -y
   ```

2. **Configurar zonas DNS:**
   - Editar `/etc/bind/named.conf.local` e criar arquivos de zona.

3. **Abrir portas 53 TCP/UDP no firewall.**

---

### 🧩 **5. Portal Web**
**Objetivo:** Servir o portal principal da aplicação.

**Passos:**
1. **Escolher stack (ex: Node.js, PHP, Python).**
2. **Configurar o serviço na porta 8080 (ou outra) para ser acessado via HAProxy.**
3. **Deploy contínuo via GitHub Actions (ver abaixo).**

---

### 🔄 **6. Integração com GitHub**
**Objetivo:** Automatizar deploys com CI/CD.

**Passos:**
1. **Criar workflow no GitHub Actions:**
   Exemplo `.github/workflows/deploy.yml`:
   ```yaml
   name: Deploy

   on:
     push:
       branches: [ "main" ]

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - name: Deploy via SSH
           uses: appleboy/ssh-action@v1.0.0
           with:
             host: ${{ secrets.SERVER_IP }}
             username: ${{ secrets.USERNAME }}
             key: ${{ secrets.SSH_KEY }}
             script: |
               cd /caminho/do/projeto
               git pull origin main
               systemctl restart portal
   ```

2. **Adicionar secrets no GitHub (SSH_KEY, SERVER_IP, etc).**

---

### ✅ **Checklist Final**
- [ ] HAProxy com SSL configurado
- [ ] Postfix + Dovecot + Roundcube funcionando
- [ ] DNS com Bind9 ativo
- [ ] Portal Web acessível via proxy
- [ ] CI/CD com GitHub Actions

Perfeito! Como você está usando **Docker** para orquestrar todos os serviços (HAProxy, e-mail, DNS, portal, etc.), vou te passar uma **estrutura de diretórios organizada** com os principais arquivos necessários para subir essa infraestrutura com **Docker Compose**.

---

### 📁 **Estrutura de Pastas Sugerida**

```
infra/
├── docker-compose.yml
├── .env
├── haproxy/
│   ├── haproxy.cfg
│   └── certs/
│       └── seu-dominio.com.pem
├── mail/
│   ├── Dockerfile
│   └── config/
│       ├── postfix/
│       └── dovecot/
├── webmail/
│   └── Dockerfile
├── dns/
│   ├── Dockerfile
│   └── named.conf
├── portal/
│   ├── Dockerfile
│   └── app/
│       └── index.html
├── github-actions/
│   └── deploy.yml
```

---

### 🧩 **Explicação dos Componentes**

#### `docker-compose.yml`
Arquivo principal que orquestra todos os containers.

#### `.env`
Armazena variáveis sensíveis como domínios, senhas, etc.

#### `haproxy/`
Contém a configuração do HAProxy e os certificados SSL.

#### `mail/`
Contém a configuração do servidor de e-mail (Postfix + Dovecot).

#### `webmail/`
Container para o Webmail (ex: Roundcube).

#### `dns/`
Servidor DNS com Bind9 ou outro.

#### `portal/`
Aplicação principal (pode ser Node.js, PHP, etc.).

#### `github-actions/`
Workflow de CI/CD para deploy automático via GitHub.
